switch to 0.
CORE:PART:GETMODULE("kOSProcessor"):DOEVENT("Open Terminal").

LOCK  THROTTLE TO 1.
LOCK STEERING TO UP.
STAGE.
WAIT UNTIL ALT:APOAPSIS > 80000.

LOCK  THROTTLE TO 0.
SET WARPMODE TO "PHYSICS".
SET WARP TO 3.
WAIT UNTIL VERTICALSPEED < -100.
SET WARP TO 0.


run Landing.