RUNONCEPATH("Defaults").
WAIT 0.1.
STAGE.
WAIT 0.5.
SAS OFF.
LOCK STEERING TO RETROGRADE.
RUNONCEPATH("Unwieldy").
//HUDTEXT("Ignition!2", 5, 2, 50, red, true).
WAIT UNTIL VANG(RETROGRADE:VECTOR, SHIP:FACING:VECTOR) < 5.
UNLOCK STEERING.
SAS ON.
WAIT 0.5.
SET SASMODE TO "RETROGRADE".
set thrustLevel to 1.
WAIT UNTIL ETA:APOAPSIS > 1 AND ETA:APOAPSIS < 20000.